name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push or pull request events but
  # only for the default branch.
  push:
    branches:
      main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install Rust packages
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo "rust-lang/mdBook" --bin mdbook --to ~/.cargo/bin
          curl --proto '=https' --tlsv1.2 -sSf https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo "badboy/mdbook-toc" --to ~/.cargo/bin
      - name: Install gh-pages
        run: |
          npm install gh-pages@"~4.0.0"
      - name: Build book
        run: |
            mdbook --version
            mdbook-toc --version
            mdbook build
      - name: Set Git config
        run: |
          git config --global user.email 'flodolo@users.noreply.github.com'
          git config --global user.name 'Francesco Lodolo [:flod]'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Deploy to GitHub pages
        run: |
          npx gh-pages --message "Deploy docs" --no-history --dist book
