name: Docs Linter

on:
  # Triggers the workflow on push or pull request events but
  # only for the default branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v5
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Run markdown linter
        run: |
          npm install
          npm test
      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Check SUMMARY.md
        run: |
          python .github/scripts/check_summary.py src
